Decode functions
ufcg-lsd/zepa-machine pull request #15
Opened 2024-09-20 05:44 UTC by filipe1417

2024-09-20 22:25 UTC, thiagomanel commented on zepa.go
> +func (m *Machine) checkRType(instruction uint32) bool {
this sounds complicated to me. I'd would expected something like:
1. a function to parse and return the opcode only
2. a switch based on the opcode to call the correct decode function

switch opcode {
    case ADD, SUB, CMP:
        return decodeRTypeInst(instruction)
    case //here the other opcodes:
        return decodeITypeInst(instruction)
    }

2024-09-20 22:28 UTC, thiagomanel requested changes
overall, it seems ok. Anyway, I think we can harness our iotas better

2024-09-21 02:57 UTC, GeraldoSJr approved these changes

2024-09-24 01:05 UTC, GeraldoSJr requested changes
Missings tests for failed cases, in which you pass parameters that should fail, the code seems to expect only "right" tries.

2024-09-24 01:05 UTC, GeraldoSJr commented on zepa.go
> +	return Opcode(opcode)
This function should return an error if the opcode provided cannot be mapped to one of the options, even if the assembler checks this on a higher level changes will happen and is safe to add this check.

2024-09-24 01:05 UTC, GeraldoSJr commented on zepa.go
> +func (m *Machine) decodeRTypeInst(instruction uint32) Instruction {
Should return an error checking the operands

2024-09-24 01:05 UTC, GeraldoSJr commented on zepa.go
> +	offsetOpcode := word - opcodeLength
Should return an error checking the operands

2025-01-10 02:30 UTC, closed without merging